package com.example.fantasystore.domain

data class Currency(
    val code: String,
    val name: String,
    val country: String,
    val flag: String
)

val currenciesList = listOf(
    Currency("AED", "UAE Dirham", "United Arab Emirates", "🇦🇪"),
    Currency("AFN", "Afghan Afghani", "Afghanistan", "🇦🇫"),
    Currency("ALL", "Albanian Lek", "Albania", "🇦🇱"),
    Currency("AMD", "Armenian Dram", "Armenia", "🇦🇲"),
    Currency("ANG", "Netherlands Antillian Guilder", "Netherlands Antilles", "🇳🇱"),
    Currency("AOA", "Angolan Kwanza", "Angola", "🇦🇴"),
    Currency("ARS", "Argentine Peso", "Argentina", "🇦🇷"),
    Currency("AUD", "Australian Dollar", "Australia", "🇦🇺"),
    Currency("AWG", "Aruban Florin", "Aruba", "🇦🇼"),
    Currency("AZN", "Azerbaijani Manat", "Azerbaijan", "🇦🇿"),
    Currency("BAM", "Bosnia and Herzegovina Mark", "Bosnia and Herzegovina", "🇧🇦"),
    Currency("BBD", "Barbados Dollar", "Barbados", "🇧🇧"),
    Currency("BDT", "Bangladeshi Taka", "Bangladesh", "🇧🇩"),
    Currency("BGN", "Bulgarian Lev", "Bulgaria", "🇧🇬"),
    Currency("BHD", "Bahraini Dinar", "Bahrain", "🇧🇭"),
    Currency("BIF", "Burundian Franc", "Burundi", "🇧🇮"),
    Currency("BMD", "Bermudian Dollar", "Bermuda", "🇧🇲"),
    Currency("BND", "Brunei Dollar", "Brunei", "🇧🇳"),
    Currency("BOB", "Bolivian Boliviano", "Bolivia", "🇧🇴"),
    Currency("BRL", "Brazilian Real", "Brazil", "🇧🇷"),
    Currency("BSD", "Bahamian Dollar", "Bahamas", "🇧🇸"),
    Currency("BTN", "Bhutanese Ngultrum", "Bhutan", "🇧🇹"),
    Currency("BWP", "Botswana Pula", "Botswana", "🇧🇼"),
    Currency("BYN", "Belarusian Ruble", "Belarus", "🇧🇾"),
    Currency("BZD", "Belize Dollar", "Belize", "🇧🇿"),
    Currency("CAD", "Canadian Dollar", "Canada", "🇨🇦"),
    Currency("CDF", "Congolese Franc", "Democratic Republic of the Congo", "🇨🇩"),
    Currency("CHF", "Swiss Franc", "Switzerland", "🇨🇭"),
    Currency("CLP", "Chilean Peso", "Chile", "🇨🇱"),
    Currency("CNY", "Chinese Renminbi", "China", "🇨🇳"),
    Currency("COP", "Colombian Peso", "Colombia", "🇨🇴"),
    Currency("CRC", "Costa Rican Colon", "Costa Rica", "🇨🇷"),
    Currency("CUP", "Cuban Peso", "Cuba", "🇨🇺"),
    Currency("CVE", "Cape Verdean Escudo", "Cape Verde", "🇨🇻"),
    Currency("CZK", "Czech Koruna", "Czech Republic", "🇨🇿"),
    Currency("DJF", "Djiboutian Franc", "Djibouti", "🇩🇯"),
    Currency("DKK", "Danish Krone", "Denmark", "🇩🇰"),
    Currency("DOP", "Dominican Peso", "Dominican Republic", "🇩🇴"),
    Currency("DZD", "Algerian Dinar", "Algeria", "🇩🇿"),
    Currency("EGP", "Egyptian Pound", "Egypt", "🇪🇬"),
    Currency("ERN", "Eritrean Nakfa", "Eritrea", "🇪🇷"),
    Currency("ETB", "Ethiopian Birr", "Ethiopia", "🇪🇹"),
    Currency("EUR", "Euro", "European Union", "🇪🇺"),
    Currency("FJD", "Fiji Dollar", "Fiji", "🇫🇯"),
    Currency("FKP", "Falkland Islands Pound", "Falkland Islands", "🇫🇰"),
    Currency("FOK", "Faroese Króna", "Faroe Islands", "🇫🇴"),
    Currency("GBP", "Pound Sterling", "United Kingdom", "🇬🇧"),
    Currency("GEL", "Georgian Lari", "Georgia", "🇬🇪"),
    Currency("GGP", "Guernsey Pound", "Guernsey", "🇬🇬"),
    Currency("GHS", "Ghanaian Cedi", "Ghana", "🇬🇭"),
    Currency("GIP", "Gibraltar Pound", "Gibraltar", "🇬🇮"),
    Currency("GMD", "Gambian Dalasi", "The Gambia", "🇬🇲"),
    Currency("GNF", "Guinean Franc", "Guinea", "🇬🇳"),
    Currency("GTQ", "Guatemalan Quetzal", "Guatemala", "🇬🇹"),
    Currency("GYD", "Guyanese Dollar", "Guyana", "🇬🇾"),
    Currency("HKD", "Hong Kong Dollar", "Hong Kong", "🇭🇰"),
    Currency("HNL", "Honduran Lempira", "Honduras", "🇭🇳"),
    Currency("HRK", "Croatian Kuna", "Croatia", "🇭🇷"),
    Currency("HTG", "Haitian Gourde", "Haiti", "🇭🇹"),
    Currency("HUF", "Hungarian Forint", "Hungary", "🇭🇺"),
    Currency("IDR", "Indonesian Rupiah", "Indonesia", "🇮🇩"),
    Currency("ILS", "Israeli New Shekel", "Israel", "🇮🇱"),
    Currency("IMP", "Manx Pound", "Isle of Man", "🇮🇲"),
    Currency("INR", "Indian Rupee", "India", "🇮🇳"),
    Currency("IQD", "Iraqi Dinar", "Iraq", "🇮🇶"),
    Currency("IRR", "Iranian Rial", "Iran", "🇮🇷"),
    Currency("ISK", "Icelandic Króna", "Iceland", "🇮🇸"),
    Currency("JEP", "Jersey Pound", "Jersey", "🇯🇪"),
    Currency("JMD", "Jamaican Dollar", "Jamaica", "🇯🇲"),
    Currency("JOD", "Jordanian Dinar", "Jordan", "🇯🇴"),
    Currency("JPY", "Japanese Yen", "Japan", "🇯🇵"),
    Currency("KES", "Kenyan Shilling", "Kenya", "🇰🇪"),
    Currency("KGS", "Kyrgyzstani Som", "Kyrgyzstan", "🇰🇬"),
    Currency("KHR", "Cambodian Riel", "Cambodia", "🇰🇭"),
    Currency("KID", "Kiribati Dollar", "Kiribati", "🇰🇮"),
    Currency("KMF", "Comorian Franc", "Comoros", "🇰🇲"),
    Currency("KRW", "South Korean Won", "South Korea", "🇰🇷"),
    Currency("KWD", "Kuwaiti Dinar", "Kuwait", "🇰🇼"),
    Currency("KYD", "Cayman Islands Dollar", "Cayman Islands", "🇰🇾"),
    Currency("KZT", "Kazakhstani Tenge", "Kazakhstan", "🇰🇿"),
    Currency("LAK", "Lao Kip", "Laos", "🇱🇦"),
    Currency("LBP", "Lebanese Pound", "Lebanon", "🇱🇧"),
    Currency("LKR", "Sri Lanka Rupee", "Sri Lanka", "🇱🇰"),
    Currency("LRD", "Liberian Dollar", "Liberia", "🇱🇷"),
    Currency("LSL", "Lesotho Loti", "Lesotho", "🇱🇸"),
    Currency("LYD", "Libyan Dinar", "Libya", "🇱🇾"),
    Currency("MAD", "Moroccan Dirham", "Morocco", "🇲🇦"),
    Currency("MDL", "Moldovan Leu", "Moldova", "🇲🇩"),
    Currency("MGA", "Malagasy Ariary", "Madagascar", "🇲🇬"),
    Currency("MKD", "Macedonian Denar", "North Macedonia", "🇲🇰"),
    Currency("MMK", "Burmese Kyat", "Myanmar", "🇲🇲"),
    Currency("MNT", "Mongolian Tögrög", "Mongolia", "🇲🇳"),
    Currency("MOP", "Macanese Pataca", "Macau", "🇲🇴"),
    Currency("MRU", "Mauritanian Ouguiya", "Mauritania", "🇲🇷"),
    Currency("MUR", "Mauritian Rupee", "Mauritius", "🇲🇺"),
    Currency("MVR", "Maldivian Rufiyaa", "Maldives", "🇲🇻"),
    Currency("MWK", "Malawian Kwacha", "Malawi", "🇲🇼"),
    Currency("MXN", "Mexican Peso", "Mexico", "🇲🇽"),
    Currency("MYR", "Malaysian Ringgit", "Malaysia", "🇲🇾"),
    Currency("MZN", "Mozambican Metical", "Mozambique", "🇲🇿"),
    Currency("NAD", "Namibian Dollar", "Namibia", "🇳🇦"),
    Currency("NGN", "Nigerian Naira", "Nigeria", "🇳🇬"),
    Currency("NIO", "Nicaraguan Córdoba", "Nicaragua", "🇳🇮"),
    Currency("NOK", "Norwegian Krone", "Norway", "🇳🇴"),
    Currency("NPR", "Nepalese Rupee", "Nepal", "🇳🇵"),
    Currency("NZD", "New Zealand Dollar", "New Zealand", "🇳🇿"),
    Currency("OMR", "Omani Rial", "Oman", "🇴🇲"),
    Currency("PAB", "Panamanian Balboa", "Panama", "🇵🇦"),
    Currency("PEN", "Peruvian Sol", "Peru", "🇵🇪"),
    Currency("PGK", "Papua New Guinean Kina", "Papua New Guinea", "🇵🇬"),
    Currency("PHP", "Philippine Peso", "Philippines", "🇵🇭"),
    Currency("PKR", "Pakistani Rupee", "Pakistan", "🇵🇰"),
    Currency("PLN", "Polish Złoty", "Poland", "🇵🇱"),
    Currency("PYG", "Paraguayan Guaraní", "Paraguay", "🇵🇾"),
    Currency("QAR", "Qatari Riyal", "Qatar", "🇶🇦"),
    Currency("RON", "Romanian Leu", "Romania", "🇷🇴"),
    Currency("RSD", "Serbian Dinar", "Serbia", "🇷🇸"),
    Currency("RUB", "Russian Ruble", "Russia", "🇷🇺"),
    Currency("RWF", "Rwandan Franc", "Rwanda", "🇷🇼"),
    Currency("SAR", "Saudi Riyal", "Saudi Arabia", "🇸🇦"),
    Currency("SBD", "Solomon Islands Dollar", "Solomon Islands", "🇸🇧"),
    Currency("SCR", "Seychellois Rupee", "Seychelles", "🇸🇨"),
    Currency("SDG", "Sudanese Pound", "Sudan", "🇸🇩"),
    Currency("SEK", "Swedish Krona", "Sweden", "🇸🇪"),
    Currency("SGD", "Singapore Dollar", "Singapore", "🇸🇬"),
    Currency("SHP", "Saint Helena Pound", "Saint Helena", "🇸🇭"),
    Currency("SLE", "Sierra Leonean Leone", "Sierra Leone", "🇸🇱"),
    Currency("SOS", "Somali Shilling", "Somalia", "🇸🇴"),
    Currency("SRD", "Surinamese Dollar", "Suriname", "🇸🇷"),
    Currency("SSP", "South Sudanese Pound", "South Sudan", "🇸🇸"),
    Currency("STN", "São Tomé and Príncipe Dobra", "São Tomé and Príncipe", "🇸🇹"),
    Currency("SYP", "Syrian Pound", "Syria", "🇸🇾"),
    Currency("SZL", "Eswatini Lilangeni", "Eswatini", "🇸🇿"),
    Currency("THB", "Thai Baht", "Thailand", "🇹🇭"),
    Currency("TJS", "Tajikistani Somoni", "Tajikistan", "🇹🇯"),
    Currency("TMT", "Turkmenistan Manat", "Turkmenistan", "🇹🇲"),
    Currency("TND", "Tunisian Dinar", "Tunisia", "🇹🇳"),
    Currency("TOP", "Tongan Paʻanga", "Tonga", "🇹🇴"),
    Currency("TRY", "Turkish Lira", "Turkey", "🇹🇷"),
    Currency("TTD", "Trinidad and Tobago Dollar", "Trinidad and Tobago", "🇹🇹"),
    Currency("TVD", "Tuvaluan Dollar", "Tuvalu", "🇹🇻"),
    Currency("TWD", "New Taiwan Dollar", "Taiwan", "🇹🇼"),
    Currency("TZS", "Tanzanian Shilling", "Tanzania", "🇹🇿"),
    Currency("UAH", "Ukrainian Hryvnia", "Ukraine", "🇺🇦"),
    Currency("UGX", "Ugandan Shilling", "Uganda", "🇺🇬"),
    Currency("USD", "United States Dollar", "United States", "🇺🇸"),
    Currency("UYU", "Uruguayan Peso", "Uruguay", "🇺🇾"),
    Currency("UZS", "Uzbekistani So'm", "Uzbekistan", "🇺🇿"),
    Currency("VES", "Venezuelan Bolívar Soberano", "Venezuela", "🇻🇪"),
    Currency("VND", "Vietnamese Đồng", "Vietnam", "🇻🇳"),
    Currency("VUV", "Vanuatu Vatu", "Vanuatu", "🇻🇺"),
    Currency("WST", "Samoan Tālā", "Samoa", "🇼🇸"),
    Currency("XAF", "Central African CFA Franc", "CEMAC", "🇨🇫"),
    Currency("XCD", "East Caribbean Dollar", "Organisation of Eastern Caribbean States", "🇽🇨"),
    Currency("XDR", "Special Drawing Rights", "International Monetary Fund", "🌍"),
    Currency("XOF", "West African CFA franc", "CFA", "🌍"),
    Currency("XPF", "CFP Franc", "Collectivités d'Outre-Mer", "🇵🇫"),
    Currency("YER", "Yemeni Rial", "Yemen", "🇾🇪"),
    Currency("ZAR", "South African Rand", "South Africa", "🇿🇦"),
    Currency("ZMW", "Zambian Kwacha", "Zambia", "🇿🇲"),
    Currency("ZWL", "Zimbabwean Dollar", "Zimbabwe", "🇿🇼"),
)

val frankfurterCurrenciesList = listOf(
    Currency("AUD", "Australian Dollar", "Australia", "🇦🇺"),
    Currency("BGN", "Bulgarian Lev", "Bulgaria", "🇧🇬"),
    Currency("BRL", "Brazilian Real", "Brazil", "🇧🇷"),
    Currency("CAD", "Canadian Dollar", "Canada", "🇨🇦"),
    Currency("CHF", "Swiss Franc", "Switzerland", "🇨🇭"), Currency("CNY", "Chinese Renminbi", "China", "🇨🇳"),
    Currency("CZK", "Czech Koruna", "Czech Republic", "🇨🇿"),
    Currency("DKK", "Danish Krone", "Denmark", "🇩🇰"),
    Currency("EUR", "Euro", "European Union", "🇪🇺"),
    Currency("GBP", "Pound Sterling", "United Kingdom", "🇬🇧"),
    Currency("HKD", "Hong Kong Dollar", "Hong Kong", "🇭🇰"),
    Currency("HUF", "Hungarian Forint", "Hungary", "🇭🇺"),
    Currency("IDR", "Indonesian Rupiah", "Indonesia", "🇮🇩"),
    Currency("ILS", "Israeli New Shekel", "Israel", "🇮🇱"),
    Currency("INR", "Indian Rupee", "India", "🇮🇳"),
    Currency("ISK", "Icelandic Króna", "Iceland", "🇮🇸"),
    Currency("JPY", "Japanese Yen", "Japan", "🇯🇵"),
    Currency("KRW", "South Korean Won", "South Korea", "🇰🇷"),
    Currency("MXN", "Mexican Peso", "Mexico", "🇲🇽"),
    Currency("MYR", "Malaysian Ringgit", "Malaysia", "🇲🇾"),
    Currency("NOK", "Norwegian Krone", "Norway", "🇳🇴"),
    Currency("NZD", "New Zealand Dollar", "New Zealand", "🇳🇿"),
    Currency("PHP", "Philippine Peso", "Philippines", "🇵🇭"),
    Currency("PLN", "Polish Złoty", "Poland", "🇵🇱"),
    Currency("RON", "Romanian Leu", "Romania", "🇷🇴"),
    Currency("SEK", "Swedish Krona", "Sweden", "🇸🇪"),
    Currency("SGD", "Singapore Dollar", "Singapore", "🇸🇬"),
    Currency("THB", "Thai Baht", "Thailand", "🇹🇭"),
    Currency("TRY", "Turkish Lira", "Turkey", "🇹🇷"),
    Currency("USD", "United States Dollar", "United States", "🇺🇸"),
    Currency("ZAR", "South African Rand", "South Africa", "🇿🇦")
)

val topWorldCurrencyCodes = listOf("USD", "EUR", "JPY", "GBP", "CNY")

val topWorldCurrencies = currenciesList.sortedByDescending { topWorldCurrencyCodes.indexOf(it.code) }

val topFrankfurterWorldCurrencies = frankfurterCurrenciesList.sortedByDescending { topWorldCurrencyCodes.indexOf(it.code) }

val latinAmericanCurrencies = currenciesList.filter {
    it.country in listOf(
        "Argentina", "Bolivia", "Brazil", "Chile", "Colombia",
        "Costa Rica", "Cuba", "Dominican Republic", "Ecuador",
        "El Salvador", "Guatemala", "Honduras", "Mexico",
        "Nicaragua", "Panama", "Paraguay", "Peru", "Uruguay",
        "Venezuela"
    )
}.take(5)
